### PR TITLE
Fix build warnings and bump dependency versions

### PR DESCRIPTION
**Pull request by markokocic**

### CODE REVIEW

**Comment by yogthos** [comment]
👍

**Comment by yogthos** [comment]
@markokocic oh by the way would you like me to add you as a maintainer? :)

**Comment by markokocic** [comment]
@yogthos wouldn't have anything against it, though I suppose I would still keep using pull requests until I get better grasp of the project as a whole.

**Comment by yogthos** [comment]
sounds like a plan :)

**Pull request merged**
