### PR TITLE
Add support for deps-new

### PR DESCRIPTION
**Pull request by rads**
## Overview

- Add a `template.edn` file to the template root (required by `deps-new`)
- Implement custom `data-fn` and `template-fn` functions to support Selmer templates
- Add tests to compare `clj-new` and `deps-new` output (runnable using `clj -M:test` alias)

## Usage

First, install [`neil`](https://github.com/babashka/neil). Then you can generate a Kit template with Babashka:

```shell
$ time neil new io.github.kit-clj/kit yourname/app \
  --xtdb --quartz \
  --git/url https://github.com/rads/kit.git \
  --git/sha 70e1f8e2099e3a6873353b6b5326a42d1ad8102f

Creating project from io.github.kit-clj/kit in app
neil new io.github.kit-clj/kit yourname/app --git/url  --git/sha   0.13s user 0.05s system 95% cpu 0.194 total
```

## TODO
- [x] Clean up implementation
  - I'm planning to add more tests and then go back and clean up the code
- [x] Check diff between `clj-new` and `deps-new` in tests automatically
  - Right now I'm just generating both directories and comparing them using [Kaleidoscope](https://kaleidoscope.app)
  - The output is almost exactly the same right now between the `clj-new` and `deps-new` versions, but I want to make sure this is verified by tests instead of checking manually

### CODE REVIEW

**Comment by rads** [comment]
Initial tests are passing in CI now: https://github.com/rads/kit/actions/runs/3166886325

Going to work on clean up next.

**Comment by rads** [comment]
@yogthos: This should be ready for a proper review now.

I pushed my latest changes and updated the "Usage" example to use the latest SHA. The tests are passing in my fork and should pass here once the GitHub Action is enabled:

https://github.com/rads/kit/actions/runs/3212932892

**Comment by yogthos** [comment]
@rads I think everything makes sense to me, if things look good to @nikolap I'd say it's good to merge. 👍

**Comment by nikolap** [comment]
Looks good to me as well. Sorry for the delay here

**Review by nikolap — APPROVED** [review]

**Comment by rads** [comment]
Awesome! I bumped the version of `deps-new` to `0.5.0` and [the tests are still passing in my fork](https://github.com/rads/kit/actions/runs/4346768233/jobs/7593240617). Since I added a new GitHub workflow here, you might need to approve it to get the new workflow to run in this PR.

Let me know if there's anything else you'd like me to take care of. Otherwise I'm ready to merge 🎉

**Comment by yogthos** [comment]
Everything looks good to me as well, let's merg it in. 🎉

**Pull request merged**
